# https://opentestfactory.gitlab.io/orchestrator/quickstart/
# https://opentestfactory.gitlab.io/site/specification/index.html
apiVersion: opentestfactory.org/v1alpha1
kind: Workflow
metadata:
  name: Cypress Burger-Store workflow
jobs:
  # Set the job key.  The key is displayed as the job name when
  # a job name is not provided
  keyword-driven:
    runs-on: [ssh, linux, cypress]
    steps:
    - run: echo Start testing
    - uses: actions/checkout@v2
      with:
        repository: https://github.com/nicoaugereau/burger-store.git
    - run: |
        npm ci
      working-directory: burger-store